### ISSUE TITLE
Feature request: Commit in the background?

### ISSUE THREAD

**Issue by AnandChowdhary** [benjaminadk/emojigit#6]
It would be awesome if there's a way Gitmoji Commit can make a commit in the background.

**Current behavior:**
1. User selects "Gitmoji Commit: Create Commit Message"
1. User selects emoji
1. User enters commit message
1. User presses the enter/return key
1. Terminal with git command is opened
1. User presses enter/return in the terminal
1. User closes terminal

**Proposed behavior:**
1. User selects "Gitmoji Commit: Create Commit Message"
1. User selects emoji
1. User enters commit message
1. User presses the enter/return key

This can be achieved by maybe figuring a way out to either directly make git commits (does VS Code have an API for that) or perhaps opening the terminal, making the commit, and then closing the terminal automatically?

**Comment by benjaminadk** [comment]
I like this idea. 
Maybe as an optional setting. Something like `backgroundCommit: boolean`? 

After a little research it looks like using vscode's git extension is the way to go. The extension system is cool in that an extension can use any other extension provided that it exports its api, which they do.

Possible issues with this approach are.

1. Multiple repository workspaces. If the user has more than one repo, there would have to be a way to determine which repo. Come to think of it this issue with the extension in general. I hadn't given it any thought, but my latest project is a workspace with two repos. This problem is avoided because I do the `git add` in the right directory and then immediately use the extension. So looks like there is work to do. 

2. I still have to figure out how to `ctrl-enter` the commit with the api.

**Comment by benjaminadk** [comment]
I ended up adding two new options. 

**autoCommit**
- type: **boolean**
- `true` - automatically executes `git commit` command in integrated terminal
- `false` - default. user must click enter to execute

**autoClose**
- type: **boolean**
- `true` - close terminal after automatic commit
- `false` - terminal remains open after automatic commit

This way it is possible to keep the terminal open and have `autoCommit` . Speeds things up but gives the choice to `autoClose`.

I'm not sure how users implement their git flow. I usually have a terminal or two running servers and another terminal for executing commands. I usually stage files through the command line not the built in SCM. I have a larger screen so I keep the terminals visible.

All that being said, I liked your idea because there are all kinds of preferences. Maybe someone uses a different external terminal and stages files with the built in SCM, but likes this extension. So these options would speed things up.

Let me know if you have any issues.
